[package]
name = "heureum"
version = "0.1.0"
authors = ["Thomas Sungjin Kang <ujuc@ujuc.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
